"""empty message

Revision ID: 8428a10685f3
Revises: 40c2d6a371a4
Create Date: 2022-02-07 23:40:21.500530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8428a10685f3'
down_revision = '40c2d6a371a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught',
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['user.id'], )
    )
    op.drop_table('user__pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__pokemon',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['poketeam.id'], name='user__pokemon_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user__pokemon_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'pokemon_id', name='user__pokemon_pkey')
    )
    op.drop_table('caught')
    # ### end Alembic commands ###
